FROM ubuntu:xenial

RUN apt update && apt install -y net-tools inetutils-ping ssh pdsh openssh-server vim

WORKDIR /app
COPY jre-8u211-linux-x64.tar.gz /app/
COPY hadoop-3.2.1.tar.gz /app/
COPY hosts /etc/hosts
RUN tar -C /usr/local -xz -v -f /app/jre-8u211-linux-x64.tar.gz
RUN tar -C /usr/local -xz -v -f /app/hadoop-3.2.1.tar.gz
RUN echo export JAVA_HOME=/usr/local/jre1.8.0_211 >> /root/.bashrc
RUN echo export HADOOP_HOME=/usr/local/hadoop-3.2.1 >> /root/.bashrc
RUN echo export PDSH_RCMD_TYPE=ssh >> /root/.bashrc
RUN echo export PATH=\$PATH:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin >> /root/.bashrc
RUN echo export JAVA_HOME=/usr/local/jre1.8.0_211 >> /usr/local/hadoop-3.2.1/etc/hadoop/hadoop-env.sh
RUN useradd hadoop
RUN mkdir /home/hadoop	
RUN chown hadoop /home/hadoop
#RUN su - hadoop -c "ssh-keygen -b 4096 -P \"\" -f /home/hadoop/.ssh/id_rsa"
#RUN su - hadoop -c "cp /home/hadoop/.ssh/id_rsa.pub /home/hadoop/.ssh/master.pub"
#RUN su - hadoop -c "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
RUN su - hadoop -c "echo export JAVA_HOME=/usr/local/jre1.8.0_211 >> ~/.bashrc"
RUN su - hadoop -c "echo export HADOOP_HOME=/usr/local/hadoop-3.2.1 >> ~/.bashrc"
RUN su - hadoop -c "echo export PDSH_RCMD_TYPE=ssh >> ~/.bashrc"
RUN su - hadoop -c "echo export PATH=\$PATH:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin >> ~/.bashrc"
COPY core-site.xml /usr/local/hadoop-3.2.1/etc/hadoop/core-site.xml
COPY hdfs-site.xml /usr/local/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
COPY mapred-site.xml /usr/local/hadoop-3.2.1/etc/hadoop/mapred-site.xml
COPY yarn-site.xml /usr/local/hadoop-3.2.1/etc/hadoop/yarn-site.xml
COPY workers /usr/local/hadoop-3.2.1/etc/hadoop/workers

RUN mkdir /var/run/sshd
RUN echo hadoop:teste | chpasswd -e
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
#CMD ["/usr/sbin/sshd", "-D"]
